/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobile.review;

import com.mysql.cj.callback.UsernameCallback;
import java.awt.EventQueue;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.KeyEvent;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.Collections;

/**
 *
 * @author User
 */
public class Compare extends javax.swing.JFrame {

    int a;
    int b;
    String name1;
    String name2;
    String uname;
    ArrayList array = new ArrayList();
    /**
     * Creates new form Compare
     */
    public Compare() {
        initComponents();
        setLocationRelativeTo(null);
        dataCon();
    }
    public Compare(String username) {
        initComponents();
        uname = username;
        dataCon();
        
    }
    
    //Auto Complete Functions
    private void dataCon(){
        PreparedStatement st;
        ResultSet rs;
        String query = "SELECT * FROM `phones`";
        try {           
            st = phoneCNX.getConnection().prepareStatement(query);
            rs = st.executeQuery();
            while(rs.next()){
                String Namee = rs.getString("name");
                array.add(Namee);
            }
            Collections.sort(array); 
            rs.close();
            st.close();
        } catch (Exception e) {
            
        }
    }
    
    public void autoComplete1(String txt){
        String complete ="";
        int start = txt.length();
        int last = txt.length();
        int a;
        for(a=0;a<array.size();a++){
            if(array.get(a).toString().startsWith(txt)){
                complete = array.get(a).toString();
                last = complete.length();
                break;
            }
        }
        if(last>start){
            jTextField_phone1.setText(complete);
            jTextField_phone1.setCaretPosition(last);
            jTextField_phone1.moveCaretPosition(start);
        }
    }
    public void autoComplete2(String txt){
        String complete ="";
        int start = txt.length();
        int last = txt.length();
        int a;
        for(a=0;a<array.size();a++){
            if(array.get(a).toString().startsWith(txt)){
                complete = array.get(a).toString();
                last = complete.length();
                break;
            }
        }
        if(last>start){
            jTextField_phone2.setText(complete);
            jTextField_phone2.setCaretPosition(last);
            jTextField_phone2.moveCaretPosition(start);
        }
    }
    //Auto Complete Ends

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_home = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel_print = new javax.swing.JLabel();
        jLabel_signout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_phone1 = new javax.swing.JTextField();
        jTextField_phone2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_cam1 = new javax.swing.JTextField();
        jTextField_pro1 = new javax.swing.JTextField();
        jTextField_ram1 = new javax.swing.JTextField();
        jTextField_rom1 = new javax.swing.JTextField();
        jTextField_bat1 = new javax.swing.JTextField();
        jTextField_fing1 = new javax.swing.JTextField();
        jTextField_dis1 = new javax.swing.JTextField();
        jTextField_os1 = new javax.swing.JTextField();
        jTextField_price1 = new javax.swing.JTextField();
        jButton_enter1 = new javax.swing.JButton();
        jTextField_cam2 = new javax.swing.JTextField();
        jTextField_pro2 = new javax.swing.JTextField();
        jTextField_ram2 = new javax.swing.JTextField();
        jTextField_rom2 = new javax.swing.JTextField();
        jTextField_bat2 = new javax.swing.JTextField();
        jTextField_fing2 = new javax.swing.JTextField();
        jTextField_dis2 = new javax.swing.JTextField();
        jTextField_os2 = new javax.swing.JTextField();
        jTextField_price2 = new javax.swing.JTextField();
        jButton_enter2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton_vom = new javax.swing.JButton();
        jTextField_Result = new javax.swing.JTextField();
        jButton_refresh = new javax.swing.JButton();

        jTextField4.setFont(new java.awt.Font("Agency FB", 0, 14)); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(148, 148, 251));

        jPanel2.setBackground(new java.awt.Color(0, 0, 174));

        jLabel_home.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Design\\Home.png")); // NOI18N
        jLabel_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_homeMouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Design\\uchoice.png")); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jLabel_print.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Design\\print.png")); // NOI18N
        jLabel_print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_printMouseClicked(evt);
            }
        });

        jLabel_signout.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Design\\signout.png")); // NOI18N
        jLabel_signout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_signout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_signoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_signout, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_print, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_home, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel_home, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel_print, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel_signout, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Urbano Cond", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Choose Phone");

        jTextField_phone1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_phone1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_phone1.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        jTextField_phone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_phone1ActionPerformed(evt);
            }
        });
        jTextField_phone1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_phone1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_phone1KeyTyped(evt);
            }
        });

        jTextField_phone2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_phone2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_phone2ActionPerformed(evt);
            }
        });
        jTextField_phone2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_phone2KeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("camera");

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("processor");

        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ram");

        jLabel5.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("rom");

        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("battery");

        jLabel7.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("fingerprint");

        jLabel8.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("display");

        jLabel9.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("os");

        jLabel10.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("price");

        jTextField_cam1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jTextField_cam1.setForeground(new java.awt.Color(0, 0, 174));
        jTextField_cam1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_cam1.setDisabledTextColor(new java.awt.Color(0, 0, 174));
        jTextField_cam1.setEnabled(false);

        jTextField_pro1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jTextField_pro1.setForeground(new java.awt.Color(0, 0, 174));
        jTextField_pro1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_pro1.setDisabledTextColor(new java.awt.Color(0, 0, 174));
        jTextField_pro1.setEnabled(false);

        jTextField_ram1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jTextField_ram1.setForeground(new java.awt.Color(0, 0, 174));
        jTextField_ram1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_ram1.setDisabledTextColor(new java.awt.Color(0, 0, 174));
        jTextField_ram1.setEnabled(false);

        jTextField_rom1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jTextField_rom1.setForeground(new java.awt.Color(0, 0, 174));
        jTextField_rom1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_rom1.setDisabledTextColor(new java.awt.Color(0, 0, 174));
        jTextField_rom1.setEnabled(false);
        jTextField_rom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_rom1ActionPerformed(evt);
            }
        });

        jTextField_bat1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jTextField_bat1.setForeground(new java.awt.Color(0, 0, 174));
        jTextField_bat1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_bat1.setDisabledTextColor(new java.awt.Color(0, 0, 174));
        jTextField_bat1.setEnabled(false);
        jTextField_bat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_bat1ActionPerformed(evt);
            }
        });

        jTextField_fing1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jTextField_fing1.setForeground(new java.awt.Color(0, 0, 174));
        jTextField_fing1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_fing1.setDisabledTextColor(new java.awt.Color(0, 0, 174));
        jTextField_fing1.setEnabled(false);

        jTextField_dis1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jTextField_dis1.setForeground(new java.awt.Color(0, 0, 174));
        jTextField_dis1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_dis1.setDisabledTextColor(new java.awt.Color(0, 0, 174));
        jTextField_dis1.setEnabled(false);

        jTextField_os1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jTextField_os1.setForeground(new java.awt.Color(0, 0, 174));
        jTextField_os1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_os1.setDisabledTextColor(new java.awt.Color(0, 0, 174));
        jTextField_os1.setEnabled(false);

        jTextField_price1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jTextField_price1.setForeground(new java.awt.Color(0, 0, 174));
        jTextField_price1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField_price1.setDisabledTextColor(new java.awt.Color(0, 0, 174));
        jTextField_price1.setEnabled(false);

        jButton_enter1.setBackground(new java.awt.Color(0, 0, 174));
        jButton_enter1.setFont(new java.awt.Font("Urbano Cond", 0, 18)); // NOI18N
        jButton_enter1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_enter1.setText("Enter");
        jButton_enter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_enter1ActionPerformed(evt);
            }
        });
        jButton_enter1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton_enter1KeyPressed(evt);
            }
        });

        jTextField_cam2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jTextField_cam2.setForeground(new java.awt.Color(0, 0, 174));
        jTextField_cam2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_cam2.setDisabledTextColor(new java.awt.Color(0, 0, 174));
        jTextField_cam2.setEnabled(false);

        jTextField_pro2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jTextField_pro2.setForeground(new java.awt.Color(0, 0, 174));
        jTextField_pro2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_pro2.setDisabledTextColor(new java.awt.Color(0, 0, 174));
        jTextField_pro2.setEnabled(false);

        jTextField_ram2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jTextField_ram2.setForeground(new java.awt.Color(0, 0, 174));
        jTextField_ram2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_ram2.setDisabledTextColor(new java.awt.Color(0, 0, 174));
        jTextField_ram2.setEnabled(false);

        jTextField_rom2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jTextField_rom2.setForeground(new java.awt.Color(0, 0, 174));
        jTextField_rom2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_rom2.setDisabledTextColor(new java.awt.Color(0, 0, 174));
        jTextField_rom2.setEnabled(false);

        jTextField_bat2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jTextField_bat2.setForeground(new java.awt.Color(0, 0, 174));
        jTextField_bat2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_bat2.setDisabledTextColor(new java.awt.Color(0, 0, 174));
        jTextField_bat2.setEnabled(false);

        jTextField_fing2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jTextField_fing2.setForeground(new java.awt.Color(0, 0, 174));
        jTextField_fing2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_fing2.setDisabledTextColor(new java.awt.Color(0, 0, 174));
        jTextField_fing2.setEnabled(false);

        jTextField_dis2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jTextField_dis2.setForeground(new java.awt.Color(0, 0, 174));
        jTextField_dis2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_dis2.setDisabledTextColor(new java.awt.Color(0, 0, 174));
        jTextField_dis2.setEnabled(false);

        jTextField_os2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jTextField_os2.setForeground(new java.awt.Color(0, 0, 174));
        jTextField_os2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_os2.setDisabledTextColor(new java.awt.Color(0, 0, 174));
        jTextField_os2.setEnabled(false);

        jTextField_price2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jTextField_price2.setForeground(new java.awt.Color(0, 0, 174));
        jTextField_price2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField_price2.setDisabledTextColor(new java.awt.Color(0, 0, 174));
        jTextField_price2.setEnabled(false);

        jButton_enter2.setBackground(new java.awt.Color(0, 0, 174));
        jButton_enter2.setFont(new java.awt.Font("Urbano Cond", 0, 18)); // NOI18N
        jButton_enter2.setForeground(new java.awt.Color(204, 204, 255));
        jButton_enter2.setText("Enter");
        jButton_enter2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_enter2ActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Design\\smartphone 1 logo.png")); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Design\\smartphone 2 logo.png")); // NOI18N

        jButton_vom.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Design\\vom.png")); // NOI18N
        jButton_vom.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_vom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_vom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_vomActionPerformed(evt);
            }
        });

        jTextField_Result.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jTextField_Result.setForeground(new java.awt.Color(0, 0, 204));
        jTextField_Result.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Result.setText("RESULT HERE");
        jTextField_Result.setDisabledTextColor(new java.awt.Color(0, 0, 204));
        jTextField_Result.setEnabled(false);

        jButton_refresh.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jButton_refresh.setText("Refresh");
        jButton_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTextField_pro1)
                                                .addGap(68, 68, 68))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTextField_cam1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jButton_enter1))
                                            .addComponent(jTextField_dis1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_os1)
                                            .addComponent(jTextField_price1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_ram1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_rom1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_bat1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_fing1, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(68, 68, 68)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel4))
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(jButton_refresh))
                                        .addGap(1, 1, 1)))
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_cam2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_pro2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_ram2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_rom2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_bat2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_fing2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_dis2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_os2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_price2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_enter2, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_phone1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addComponent(jLabel1)
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_phone2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(56, 56, 56))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_vom, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Result))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField_phone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_phone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_cam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_cam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField_pro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_pro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_ram1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_ram2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_rom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField_rom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_bat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField_bat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_fing1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField_fing2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_dis1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField_dis2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_os1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_os2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_price1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addComponent(jTextField_price2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_enter1)
                    .addComponent(jButton_enter2)
                    .addComponent(jButton_refresh))
                .addGap(18, 18, 18)
                .addComponent(jButton_vom, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField_Result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_phone2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_phone2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_phone2ActionPerformed

    private void jTextField_phone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_phone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_phone1ActionPerformed

    private void jButton_enter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_enter1ActionPerformed
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet rs;
        name1 = jTextField_phone1.getText();
        //String name2 = jTextField_phone2.getText();
        String query = "SELECT * FROM `phones` WHERE `name` = ?";
        try {
            st = phoneCNX.getConnection().prepareStatement(query);
            st.setString(1, name1);
            rs = st.executeQuery();
            if (rs.next()) {
                jTextField_cam1.setText(rs.getString("camera"));
                jTextField_pro1.setText(rs.getString("processor"));
                jTextField_ram1.setText(rs.getString("ram"));
                jTextField_rom1.setText(rs.getString("rom"));
                jTextField_bat1.setText(rs.getString("battery"));
                jTextField_fing1.setText(rs.getString("fingerprint"));
                jTextField_dis1.setText(rs.getString("display"));
                jTextField_os1.setText(rs.getString("os"));
                jTextField_price1.setText(rs.getString("price")+" BDT");
                a = rs.getInt("value");  
            }
            else{
                JOptionPane.showMessageDialog(null, "Mobile Not Found! Check the NAME again!", "NOT FOUND!", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton_enter1ActionPerformed

    private void jTextField_bat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_bat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_bat1ActionPerformed

    private void jTextField_rom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_rom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_rom1ActionPerformed

    private void jButton_enter2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_enter2ActionPerformed
        // TODO add your handling code here:
        PreparedStatement st;
        ResultSet rs;
        name2 = jTextField_phone2.getText();
        String query = "SELECT * FROM `phones` WHERE `name` = ?";
        try {
            st = phoneCNX.getConnection().prepareStatement(query);
            st.setString(1, name2);
            //st.setString(2, name2);
            rs = st.executeQuery();
            if (rs.next()) {
                jTextField_cam2.setText(rs.getString("camera"));
                jTextField_pro2.setText(rs.getString("processor"));
                jTextField_ram2.setText(rs.getString("ram"));
                jTextField_rom2.setText(rs.getString("rom"));
                jTextField_bat2.setText(rs.getString("battery"));
                jTextField_fing2.setText(rs.getString("fingerprint"));
                jTextField_dis2.setText(rs.getString("display"));
                jTextField_os2.setText(rs.getString("os"));
                jTextField_price2.setText(rs.getString("price")+" BDT");
                b = rs.getInt("value");
            }
            else{
                JOptionPane.showMessageDialog(null, "Mobile Not Found! Check the NAME again!", "NOT FOUND!", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton_enter2ActionPerformed

    private void jTextField_phone1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_phone1KeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField_phone1KeyTyped

    private void jLabel_printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_printMouseClicked
        // TODO add your handling code here:
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setJobName("Print Data");

        job.setPrintable(new Printable() {
            public int print(Graphics pg, PageFormat pf, int pageNum) {
                pf.setOrientation(PageFormat.LANDSCAPE);
                if (pageNum > 0) {
                    return Printable.NO_SUCH_PAGE;
                }
                Graphics2D g2 = (Graphics2D) pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47, 0.47);
                jPanel1.print(g2);
                return Printable.PAGE_EXISTS;
            }
        });
        boolean ok = job.printDialog();
        if (ok) {
            try {

                job.print();
            } catch (PrinterException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jLabel_printMouseClicked

    private void jLabel_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_homeMouseClicked
        // TODO add your handling code here:
        SignIn si = new SignIn(uname,"");
        si.setVisible(true);
        si.pack();
        si.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel_homeMouseClicked

    private void jLabel_signoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_signoutMouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do you really want to sign out?","SIGN OUT",JOptionPane.YES_NO_OPTION);
        if(a == 0){
            Login log = new Login();
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        this.dispose();
        }
        
    }//GEN-LAST:event_jLabel_signoutMouseClicked

    private void jButton_enter1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton_enter1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_enter1KeyPressed

    private void jTextField_phone1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_phone1KeyPressed
        // TODO add your handling code here:
        //Code To Press Enter
        /*if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            PreparedStatement st;
            ResultSet rs;
            name1 = jTextField_phone1.getText();
            //String name2 = jTextField_phone2.getText();
            String query = "SELECT * FROM `phones` WHERE `name` = ?";
            try {
                st = phoneCNX.getConnection().prepareStatement(query);
                st.setString(1, name1);
                rs = st.executeQuery();
                if (rs.next()) {
                    jTextField_cam1.setText(rs.getString("camera"));
                    jTextField_pro1.setText(rs.getString("processor"));
                    jTextField_ram1.setText(rs.getString("ram"));
                    jTextField_rom1.setText(rs.getString("rom"));
                    jTextField_bat1.setText(rs.getString("battery"));
                    jTextField_fing1.setText(rs.getString("fingerprint"));
                    jTextField_dis1.setText(rs.getString("display"));
                    jTextField_os1.setText(rs.getString("os"));
                    jTextField_price1.setText(rs.getString("price")+" BDT");
                    a = rs.getInt("value");
                }
                else{
                JOptionPane.showMessageDialog(null, "Mobile Not Found! Check the NAME again!", "NOT FOUND!", JOptionPane.WARNING_MESSAGE);
            }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }*/
        switch(evt.getKeyCode()){
            case KeyEvent.VK_BACK_SPACE:
                break;
            case KeyEvent.VK_ENTER:
                jTextField_phone1.setText(jTextField_phone1.getText());
                break;
            default:
                EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                String txt = jTextField_phone1.getText();
                autoComplete1(txt);
            }              
                });
        }
    }//GEN-LAST:event_jTextField_phone1KeyPressed

    private void jTextField_phone2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_phone2KeyPressed
        // TODO add your handling code here:
        /*if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            PreparedStatement st;
            ResultSet rs;
            name2 = jTextField_phone2.getText();
            String query = "SELECT * FROM `phones` WHERE `name` = ?";
            try {
                st = phoneCNX.getConnection().prepareStatement(query);
                st.setString(1, name2);
                //st.setString(2, name2);
                rs = st.executeQuery();
                if (rs.next()) {
                    jTextField_cam2.setText(rs.getString("camera"));
                    jTextField_pro2.setText(rs.getString("processor"));
                    jTextField_ram2.setText(rs.getString("ram"));
                    jTextField_rom2.setText(rs.getString("rom"));
                    jTextField_bat2.setText(rs.getString("battery"));
                    jTextField_fing2.setText(rs.getString("fingerprint"));
                    jTextField_dis2.setText(rs.getString("display"));
                    jTextField_os2.setText(rs.getString("os"));
                    jTextField_price2.setText(rs.getString("price")+" BDT");
                    b = rs.getInt("value");
                }
                else{
                JOptionPane.showMessageDialog(null, "Mobile Not Found! Check the NAME again!", "NOT FOUND!", JOptionPane.WARNING_MESSAGE);
            }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }*/
        
        switch(evt.getKeyCode()){
            case KeyEvent.VK_BACK_SPACE:
                break;
            case KeyEvent.VK_ENTER:
                jTextField_phone2.setText(jTextField_phone2.getText());
                break;
            default:
                EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                String txt = jTextField_phone2.getText();
                autoComplete2(txt);
            }              
                });
        }

    }//GEN-LAST:event_jTextField_phone2KeyPressed

    private void jButton_vomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_vomActionPerformed
        // TODO add your handling code here:
        if(a>b){
            jTextField_Result.setText(name1);
        }
        else if(b>a)
            jTextField_Result.setText(name2);
        else{
            jTextField_Result.setText("Both are equal!");
        } 
            
        
    }//GEN-LAST:event_jButton_vomActionPerformed

    private void jButton_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_refreshActionPerformed
        // TODO add your handling code here:
        jTextField_phone1.setText("");
        jTextField_phone2.setText("");
        jTextField_cam1.setText("");
        jTextField_cam2.setText("");
        jTextField_pro1.setText("");
        jTextField_pro2.setText("");
        jTextField_ram1.setText("");
        jTextField_ram2.setText("");
        jTextField_rom1.setText("");
        jTextField_rom2.setText("");
        jTextField_bat1.setText("");
        jTextField_bat2.setText("");
        jTextField_fing1.setText("");
        jTextField_fing2.setText("");
        jTextField_dis1.setText("");
        jTextField_dis2.setText("");
        jTextField_os1.setText("");
        jTextField_os2.setText("");
        jTextField_price1.setText("");
        jTextField_price2.setText("");
        jTextField_Result.setText("");
        
        
    }//GEN-LAST:event_jButton_refreshActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        Searchuser su = new Searchuser(uname);
        su.setVisible(true);
        su.setLocationRelativeTo(null);
        su.pack();
        this.dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compare.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Compare().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_enter1;
    private javax.swing.JButton jButton_enter2;
    private javax.swing.JButton jButton_refresh;
    private javax.swing.JButton jButton_vom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_home;
    private javax.swing.JLabel jLabel_print;
    private javax.swing.JLabel jLabel_signout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField_Result;
    private javax.swing.JTextField jTextField_bat1;
    private javax.swing.JTextField jTextField_bat2;
    private javax.swing.JTextField jTextField_cam1;
    private javax.swing.JTextField jTextField_cam2;
    private javax.swing.JTextField jTextField_dis1;
    private javax.swing.JTextField jTextField_dis2;
    private javax.swing.JTextField jTextField_fing1;
    private javax.swing.JTextField jTextField_fing2;
    private javax.swing.JTextField jTextField_os1;
    private javax.swing.JTextField jTextField_os2;
    private javax.swing.JTextField jTextField_phone1;
    private javax.swing.JTextField jTextField_phone2;
    private javax.swing.JTextField jTextField_price1;
    private javax.swing.JTextField jTextField_price2;
    private javax.swing.JTextField jTextField_pro1;
    private javax.swing.JTextField jTextField_pro2;
    private javax.swing.JTextField jTextField_ram1;
    private javax.swing.JTextField jTextField_ram2;
    private javax.swing.JTextField jTextField_rom1;
    private javax.swing.JTextField jTextField_rom2;
    // End of variables declaration//GEN-END:variables
}
