/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobile.review;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import net.miginfocom.swing.MigLayout;


/**
 *
 * @author User
 */
public class PanelSearch extends javax.swing.JPanel {

    private EventClick event;
    
    public void addClickEvent(EventClick event){
        this.event = event;
    }
    
    public PanelSearch() {
        initComponents();
        setLayout(new MigLayout("fillx", "0[]0", "0[]0"));
    }
    public void setData(List<DataSearch> data){
        this.removeAll();
        for(DataSearch d:data){
            Search_item item = new Search_item(d);
            //add event
            item.addEvent(new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent ae){
                    event.itemClick(d);
                }
            }, new ActionListener(){
                @Override
                public void actionPerformed(ActionEvent ae){
                    event.itemRemove(item, d);
                }
            });
            this.add(item, "wrap");
        }
        repaint();
        revalidate();
    }
    
    public int getItemSize(){
        return getComponentCount();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
