/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobile.review;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import java.util.Collections;

/**
 *
 * @author User
 */
public class Searchuser extends javax.swing.JFrame {

    PreparedStatement st;
        ResultSet rs;
        String username;
        ArrayList array = new ArrayList();
        
    /**
     * Creates new form Searchuser
     */
    public Searchuser() {
        initComponents();
        setLocationRelativeTo(null);
        dataCon();
    }
    public Searchuser(String un) {
        initComponents();
        setLocationRelativeTo(null);
        username = un;
        jLabel_user.setText(un);
        dataCon();
        
    }
    
    //Auto Complete Functions
    private void dataCon(){
        PreparedStatement st;
        ResultSet rs;
        String query = "SELECT * FROM `user_login`";
        try {           
            st = MyConnection.getConnection().prepareStatement(query);
            rs = st.executeQuery();
            while(rs.next()){
                String Namee = rs.getString("myphone");
                array.add(Namee);
            }
            Collections.sort(array); 
            rs.close();
            st.close();
        } catch (Exception e) {
            
        }
    }
    
    public void autoComplete(String txt){
        String complete ="";
        int start = txt.length();
        int last = txt.length();
        int a;
        for(a=0;a<array.size();a++){
            if(array.get(a).toString().startsWith(txt)){
                complete = array.get(a).toString();
                last = complete.length();
                break;
            }
        }
        if(last>start){
            jTextField1.setText(complete);
            jTextField1.setCaretPosition(last);
            jTextField1.moveCaretPosition(start);
        }
    }
    //Auto Complete Ends
    
    public void showTable(){
        
        
        String query = "SELECT id,firstname,lastname,email,myphone FROM `user_login`";
        try {
            st = MyConnection.getConnection().prepareStatement(query);
            rs = st.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(Searchuser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public boolean phoneMatch(){
        PreparedStatement st;
        ResultSet rs;
        boolean matching = false;
        String data = jTextField1.getText();
        String query = "SELECT * FROM `user_login` WHERE `myphone` = ?";
        try {
            st = MyConnection.getConnection().prepareStatement(query);
            st.setString(1, data);
            rs = st.executeQuery();
            if(rs.next())
            {
                matching = true;
               
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Searchuser.class.getName()).log(Level.SEVERE, null, ex);
        }
        return matching;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_verdict = new javax.swing.JTextField();
        jTextField_users = new javax.swing.JTextField();
        jLabel_comment = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_home = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel_user = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(94, 85, 148));

        jTextField1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "FIRST NAME", "LAST NAME", "EMAIL", "PHONE", "RATING"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setFocusable(false);
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setName(""); // NOI18N
        jTable1.setRowHeight(30);
        jTable1.setSelectionBackground(new java.awt.Color(232, 57, 95));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(94, 85, 148));
        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SEARCH THE PHONE");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(94, 85, 148));
        jLabel4.setText("Final Verdict:");

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(94, 85, 148));
        jLabel5.setText("Users:");

        jTextField_verdict.setFont(new java.awt.Font("Roboto Condensed", 0, 24)); // NOI18N
        jTextField_verdict.setDisabledTextColor(new java.awt.Color(0, 0, 102));
        jTextField_verdict.setEnabled(false);

        jTextField_users.setFont(new java.awt.Font("Roboto Condensed", 0, 24)); // NOI18N
        jTextField_users.setDisabledTextColor(new java.awt.Color(0, 0, 153));
        jTextField_users.setEnabled(false);
        jTextField_users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_usersActionPerformed(evt);
            }
        });

        jLabel_comment.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_comment.setForeground(new java.awt.Color(0, 0, 102));
        jLabel_comment.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_comment.setText("verdict");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_verdict, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_users, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_comment, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_verdict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_users, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel_comment, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addContainerGap(60, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(367, 367, 367))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setForeground(new java.awt.Color(204, 51, 0));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("INSTRUCTIONS");

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Design\\infoo.png")); // NOI18N

        jLabel_home.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Design\\Home.png")); // NOI18N
        jLabel_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_homeMouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Design\\signout.png")); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel_user.setFont(new java.awt.Font("Urbano Cond", 1, 36)); // NOI18N
        jLabel_user.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_user.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_user.setText("user");
        jLabel_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_userMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_userMouseExited(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Design\\active.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_user)
                        .addGap(133, 133, 133))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel_home)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel7))))
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel_user))
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_home)
                    .addComponent(jLabel7))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        /*String data = jTextField1.getText();
        if(data.equals("")){
            JOptionPane.showMessageDialog(null, "Enter Phone Name Please");
        }
        else{    
            String query = "SELECT firstname,lastname,email,myphone,rateofphone FROM `user_login` WHERE `myphone` = ? ";
        try {
            st = MyConnection.getConnection().prepareStatement(query);
            st.setString(1, data);
            rs = st.executeQuery();
            jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 18));
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Searchuser.class.getName()).log(Level.SEVERE, null, ex);
        }
        int rowCount = jTable1.getRowCount();
            int sum = 0;
            for(int i=0;i<rowCount;i++){
                sum = sum+Integer.parseInt(jTable1.getValueAt(i, 4).toString());
            }
            int av = sum/rowCount;
            jTextField_verdict.setText(av+" out of 100");
            jTextField_users.setText(""+rowCount);
            if(av>=80){
                jLabel_comment.setText("Great Phone!");
            }
            else if(av<80 && av>=60){
                jLabel_comment.setText("Good!");
            }
            else if(av<60){
                jLabel_comment.setText("Not Recommended!");
            }
        }*/
        
        String data = jTextField1.getText();
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("FIRST NAME");
        table.addColumn("LAST NAME");
        table.addColumn("EMAIL");
        table.addColumn("PHONE");
        table.addColumn("RATING");
        if(data.equals("")){
            JOptionPane.showMessageDialog(null, "Enter Phone Name Please");
        }
        else{    
            
        try {
            String query = "SELECT firstname,lastname,email,myphone,rateofphone FROM `user_login` WHERE `myphone` = ? ";
            st = MyConnection.getConnection().prepareStatement(query);
            st.setString(1, data);
            rs = st.executeQuery();
            if(phoneMatch()){
                while(rs.next()){
                    table.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5)
                });
                    jTable1.setModel(table);
            }
            
            
            }
            
            else{
                JOptionPane.showMessageDialog(null, "Incorrect Phone Name! or No User of this Phone Found!");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Searchuser.class.getName()).log(Level.SEVERE, null, ex);
        }
        int rowCount = jTable1.getRowCount();
            int sum = 0;
            for(int i=0;i<rowCount;i++){
                sum = sum+Integer.parseInt(jTable1.getValueAt(i, 4).toString());
            }
            int av = sum/rowCount;
            jTextField_verdict.setText(av+" out of 100");
            jTextField_users.setText(""+rowCount);
            if(av>=80){
                jLabel_comment.setText("Great Phone!");
            }
            else if(av<80 && av>=60){
                jLabel_comment.setText("Good!");
            }
            else if(av<60){
                jLabel_comment.setText("Not Recommended!");
            }
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField_usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_usersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usersActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do you really want to sign out?","SIGN OUT",JOptionPane.YES_NO_OPTION);
        if(a==0){
            Login log = new Login();
            log.setVisible(true);
            log.pack();
            log.setLocationRelativeTo(null);
            log.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_homeMouseClicked
        // TODO add your handling code here:
        SignIn si = new SignIn(username,"");
        si.setVisible(true);
        si.pack();
        si.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel_homeMouseClicked

    private void jLabel_userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_userMouseEntered
        // TODO add your handling code here:
        jLabel_user.setForeground(Color.yellow);
    }//GEN-LAST:event_jLabel_userMouseEntered

    private void jLabel_userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_userMouseExited
        // TODO add your handling code here:
        jLabel_user.setForeground(Color.white);
    }//GEN-LAST:event_jLabel_userMouseExited

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_BACK_SPACE:
                break;
            case KeyEvent.VK_ENTER:
                jTextField1.setText(jTextField1.getText());
                break;
            default:
                EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                String txt = jTextField1.getText();
                autoComplete(txt);
            }              
                });
        }
    }//GEN-LAST:event_jTextField1KeyPressed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Searchuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Searchuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Searchuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Searchuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Searchuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_comment;
    private javax.swing.JLabel jLabel_home;
    private javax.swing.JLabel jLabel_user;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField_users;
    private javax.swing.JTextField jTextField_verdict;
    // End of variables declaration//GEN-END:variables
}
