/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobile.review;

import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author User
 */
public class Search_item extends javax.swing.JPanel {

    public Search_item(DataSearch data) {
        initComponents();
        setData(data);
    }
    private void setData(DataSearch data){
        addEventMouse(this);
        jLabel_txt.setText(data.getText());
        if(data.isStory()){
            jLabel_txt.setForeground(new Color(29, 106, 205));
            jLabel_remove.setCursor(new Cursor(Cursor.HAND_CURSOR));
        }
        else{
            jLabel_remove.setText("");
            
        }
    }
    
    private void addEventMouse(Component com){
        com.addMouseListener(new MouseAdapter(){
        @Override
        public void mouseEntered(MouseEvent me){
            setBackground(new Color(194,195,196));
        }
        @Override
        public void mouseExited(MouseEvent me){
            setBackground(Color.WHITE);
        }
    });
    }
    
    private ActionListener eventClick;
    private ActionListener eventRemove;
    public void addEvent(ActionListener eventClick, ActionListener eventRemove){
        this.eventClick = eventClick;
        this.eventRemove = eventRemove;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked");
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_txt = new javax.swing.JLabel();
        jLabel_remove = new javax.swing.JLabel();

        jLabel_txt.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel_txt.setText("Text Here.....");
        jLabel_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_txtMouseClicked(evt);
            }
        });

        jLabel_remove.setForeground(new java.awt.Color(102, 102, 102));
        jLabel_remove.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_remove.setText("Remove");
        jLabel_remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_removeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_remove, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(jLabel_remove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_removeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_removeMouseClicked
        // TODO add your handling code here:
        if(!jLabel_remove.getText().trim().equals("")){
            eventRemove.actionPerformed(null);
        }
        
    }//GEN-LAST:event_jLabel_removeMouseClicked

    private void jLabel_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_txtMouseClicked
        // TODO add your handling code here:
        eventClick.actionPerformed(null);
    }//GEN-LAST:event_jLabel_txtMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel_remove;
    private javax.swing.JLabel jLabel_txt;
    // End of variables declaration//GEN-END:variables
}
