/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobile.review;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class SignIn extends javax.swing.JFrame {

    String un;
    /**
     * Creates new form SignIn
     */
    public SignIn() {
        initComponents();
    }
    public SignIn(String username, String wtext){
        initComponents();
        //jLabel6.setText(username);
        un = username;
        jLabel_welcometext.setText("Hello, " + un +"!");
        jLabel4.setText(wtext);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_userprofile = new javax.swing.JLabel();
        jLabel_userschoice = new javax.swing.JLabel();
        jLabel_comparephones = new javax.swing.JLabel();
        jLabel_signout = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_welcometext = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(94, 85, 148));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Design\\Gif.gif")); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Design\\Animated Text.gif")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 690));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("You are succesfully logged in!");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, -1, 39));

        jLabel_userprofile.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Design\\user profile icn.png")); // NOI18N
        jLabel_userprofile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_userprofile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_userprofileMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_userprofile, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 194, -1, -1));

        jLabel_userschoice.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Design\\users choice.png")); // NOI18N
        jLabel_userschoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_userschoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_userschoiceMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_userschoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(863, 194, -1, -1));

        jLabel_comparephones.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Design\\compare phones.png")); // NOI18N
        jLabel_comparephones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_comparephones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_comparephonesMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_comparephones, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 351, -1, -1));

        jLabel_signout.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Design\\sign out.png")); // NOI18N
        jLabel_signout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_signout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_signoutMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_signout, new org.netbeans.lib.awtextra.AbsoluteConstraints(863, 351, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Design\\Layout1.png")); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 500, 410));

        jLabel_welcometext.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel_welcometext.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_welcometext.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_welcometext.setText("Hello!");
        jPanel1.add(jLabel_welcometext, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 290, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1188, 729));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void jLabel_userprofileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_userprofileMouseClicked
        // TODO add your handling code here:
        UserProfile up = new UserProfile(un);
        up.setVisible(true);
        up.pack();
        up.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel_userprofileMouseClicked

    private void jLabel_signoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_signoutMouseClicked
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do you really want to sign out?","SIGN OUT",JOptionPane.YES_NO_OPTION);
        if(a==0){
            Login log = new Login();
            log.setVisible(true);
            log.pack();
            log.setLocationRelativeTo(null);
            log.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
        }
            
        
    }//GEN-LAST:event_jLabel_signoutMouseClicked

    private void jLabel_comparephonesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_comparephonesMouseClicked
        // TODO add your handling code here:
        Compare comp = new Compare(un);
        comp.setVisible(true);
        comp.pack();
        comp.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jLabel_comparephonesMouseClicked

    private void jLabel_userschoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_userschoiceMouseClicked
        // TODO add your handling code here:
        Searchuser su = new Searchuser(un);
        su.setVisible(true);
        su.setLocationRelativeTo(null);
        su.pack();
        this.dispose();
    }//GEN-LAST:event_jLabel_userschoiceMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_comparephones;
    private javax.swing.JLabel jLabel_signout;
    private javax.swing.JLabel jLabel_userprofile;
    private javax.swing.JLabel jLabel_userschoice;
    private javax.swing.JLabel jLabel_welcometext;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
