/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobile.review;
import static com.sun.tools.attach.VirtualMachine.list;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import static java.nio.file.Files.list;
import java.sql.*;
import static java.util.Collections.list;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author User
 */
public class Update extends javax.swing.JFrame {

    String uname;
    /**
     * Creates new form Update
     */
    public Update() {
        initComponents();
        setLocationRelativeTo(null);
        showTable();
        
    }
    public Update(String un) {
        initComponents();
        uname = un;
        showTable();
        
        
    }
    
    public void showTable(){
        DefaultTableModel table = new DefaultTableModel();
        table.addColumn("ID");
        table.addColumn("Name");
        table.addColumn("Camera");
        table.addColumn("Processor");
        table.addColumn("RAM");
        table.addColumn("ROM");
        table.addColumn("Battery");
        table.addColumn("Finger Print");
        table.addColumn("Display");
        table.addColumn("OS");
        table.addColumn("Price");
        table.addColumn("VOM(%)");
        
        PreparedStatement st;
        ResultSet rs;
        
        String query = "SELECT id,name,camera,processor,ram,rom,battery,fingerprint,display,os,price,value FROM phones";
        try {           
            st = phoneCNX.getConnection().prepareStatement(query);
            rs = st.executeQuery();
            while(rs.next()){
                table.addRow(new Object[]{
                    rs.getString(1),
                rs.getString(2),
                rs.getString(3),
                rs.getString(4),
                rs.getString(5),
                rs.getString(6),
                rs.getString(7),
                rs.getString(8),
                rs.getString(9),
                rs.getString(10),
                rs.getString(11),
                rs.getString(12),
                });
            }
            jTable1.setModel(table);
            //jTable1.setModel(DbUtils.resultSetToTableModel(rs));
            
            //Column Auto Size
            TableColumnModel col = jTable1.getColumnModel();
            TableModel model = jTable1.getModel();
            int total = col.getColumnCount();
            for(int i=0;i<total;i++){
                int taile = 0;
                int total2 = model.getRowCount();
                for(int j=0;j<total2;j++){
                    if(model.getValueAt(j, i)!=null){
                        int taile2 = model.getValueAt(j, i).toString().length()*5;
                        if(taile2>taile){
                            taile = taile2;
                        }
                    } col.getColumn(i).setPreferredWidth(taile);
                }
            }
            
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_home = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_Name = new javax.swing.JTextField();
        jTextField_Camera = new javax.swing.JTextField();
        jTextField_Processor = new javax.swing.JTextField();
        jTextField_Ram = new javax.swing.JTextField();
        jTextField_Rom = new javax.swing.JTextField();
        jTextField_Battery = new javax.swing.JTextField();
        jTextField_FingerPrint = new javax.swing.JTextField();
        jTextField_Display = new javax.swing.JTextField();
        jTextField_os = new javax.swing.JTextField();
        jTextField_price = new javax.swing.JTextField();
        jTextField_vom = new javax.swing.JTextField();
        jButton_Update = new javax.swing.JButton();
        jButton_Delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel_home.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Desktop\\Design\\Home.png")); // NOI18N
        jLabel_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_homeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(jLabel_home, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel_home, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(533, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Camera", "Processor", "RAM", "ROM", "Battery", "Finger Print", "Display", "OS", "Price", "VOM(%)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setRowHeight(48);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Open Sans Condensed", 0, 18)); // NOI18N
        jLabel1.setText("Name:");

        jLabel2.setFont(new java.awt.Font("Open Sans Condensed", 0, 18)); // NOI18N
        jLabel2.setText("Camera:");

        jLabel3.setFont(new java.awt.Font("Open Sans Condensed", 0, 18)); // NOI18N
        jLabel3.setText("Processor:");

        jLabel4.setFont(new java.awt.Font("Open Sans Condensed", 0, 18)); // NOI18N
        jLabel4.setText("RAM:");

        jLabel5.setFont(new java.awt.Font("Open Sans Condensed", 0, 18)); // NOI18N
        jLabel5.setText("ROM:");

        jLabel6.setFont(new java.awt.Font("Open Sans Condensed", 0, 18)); // NOI18N
        jLabel6.setText("Battery:");

        jLabel7.setFont(new java.awt.Font("Open Sans Condensed", 0, 18)); // NOI18N
        jLabel7.setText("FingerPrint:");

        jLabel8.setFont(new java.awt.Font("Open Sans Condensed", 0, 18)); // NOI18N
        jLabel8.setText("Display:");

        jLabel9.setFont(new java.awt.Font("Open Sans Condensed", 0, 18)); // NOI18N
        jLabel9.setText("OS:");

        jLabel10.setFont(new java.awt.Font("Open Sans Condensed", 0, 18)); // NOI18N
        jLabel10.setText("Price:");

        jLabel11.setFont(new java.awt.Font("Open Sans Condensed", 0, 18)); // NOI18N
        jLabel11.setText("VOM (%):");

        jTextField_Name.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        jTextField_Camera.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        jTextField_Processor.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        jTextField_Ram.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        jTextField_Rom.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        jTextField_Battery.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        jTextField_FingerPrint.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        jTextField_Display.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        jTextField_os.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        jTextField_price.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        jTextField_vom.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N

        jButton_Update.setFont(new java.awt.Font("Open Sans Condensed", 0, 18)); // NOI18N
        jButton_Update.setText("UPDATE");
        jButton_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_UpdateActionPerformed(evt);
            }
        });

        jButton_Delete.setFont(new java.awt.Font("Open Sans Condensed", 0, 18)); // NOI18N
        jButton_Delete.setText("DELETE");
        jButton_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1420, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_Battery, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_Camera, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_Processor, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_Ram, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_Rom, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(64, 64, 64)
                                .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_vom, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_price, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_os, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Display, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_FingerPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton_Delete)
                                .addGap(131, 131, 131)
                                .addComponent(jButton_Update)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_FingerPrint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jTextField_Camera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)
                            .addComponent(jTextField_os, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextField_Processor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(jTextField_Ram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(jTextField_Rom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_vom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_Battery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_Update)
                        .addComponent(jButton_Delete))
                    .addComponent(jLabel6))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_homeMouseClicked
        // TODO add your handling code here:
        admin ad = new admin(uname);
        ad.setVisible(true);
        ad.pack();
        ad.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_jLabel_homeMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel)jTable1.getModel();
        String Name = table.getValueAt(jTable1.getSelectedRow(), 1).toString();
        String Camera = table.getValueAt(jTable1.getSelectedRow(), 2).toString();
        String Processor = table.getValueAt(jTable1.getSelectedRow(), 3).toString();
        String RAM = table.getValueAt(jTable1.getSelectedRow(), 4).toString();
        String ROM = table.getValueAt(jTable1.getSelectedRow(), 5).toString();
        String Battery = table.getValueAt(jTable1.getSelectedRow(), 6).toString();
        String FingerPrint = table.getValueAt(jTable1.getSelectedRow(), 7).toString();
        String Display = table.getValueAt(jTable1.getSelectedRow(), 8).toString();
        String OS = table.getValueAt(jTable1.getSelectedRow(), 9).toString();
        String Price = table.getValueAt(jTable1.getSelectedRow(), 10).toString();
        String VOM = table.getValueAt(jTable1.getSelectedRow(), 11).toString();
        jTextField_Name.setText(Name);
        jTextField_Camera.setText(Camera);
        jTextField_Processor.setText(Processor);
        jTextField_Ram.setText(RAM);
        jTextField_Rom.setText(ROM);
        jTextField_Battery.setText(Battery);
        jTextField_FingerPrint.setText(FingerPrint);
        jTextField_Display.setText(Display);
        jTextField_os.setText(OS);
        jTextField_price.setText(Price);
        jTextField_vom.setText(VOM);
        
    }//GEN-LAST:event_jTable1MouseClicked
    
    public void UpdateData(){
        PreparedStatement ps;
        ResultSet rs;
        DefaultTableModel table = (DefaultTableModel)jTable1.getModel();
        String id = table.getValueAt(jTable1.getSelectedRow(), 0).toString();
        int a = Integer.parseInt(id);
        String name = jTextField_Name.getText();
        String camera = jTextField_Camera.getText();
        String processor = jTextField_Processor.getText();
        String ram = jTextField_Ram.getText();
        String rom = jTextField_Rom.getText();
        String battery = jTextField_Battery.getText();
        String fingerprint = jTextField_FingerPrint.getText();
        String display = jTextField_Display.getText();
        String os = jTextField_os.getText();
        String price = jTextField_price.getText();
        int vom = Integer.parseInt(jTextField_vom.getText());
        String Query = "UPDATE `phones` SET `name`=?,`camera`=?,`processor`=?,`ram`=?,`rom`=?,`battery`=?,`fingerprint`=?,`display`=?,`os`=?,`price`=?,`value`=? WHERE `id`=?";
        try {
            ps = phoneCNX.getConnection().prepareStatement(Query);
            ps.setString(1, name);
            ps.setString(2, camera);
            ps.setString(3, processor);
            ps.setString(4, ram);
            ps.setString(5, rom);
            ps.setString(6, battery);
            ps.setString(7, fingerprint);
            ps.setString(8, display);
            ps.setString(9, os);
            ps.setString(10, price);
            ps.setInt(11, vom);
            ps.setInt(12, a);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully Updated! by "+uname);
            showTable();
         
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    private void jButton_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_UpdateActionPerformed
        // TODO add your handling code here:
        UpdateData();
        
    }//GEN-LAST:event_jButton_UpdateActionPerformed

    private void jButton_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DeleteActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Do you really want to Delete?","Delete?",JOptionPane.YES_NO_OPTION);
        if(a==0){
        PreparedStatement ps;
        ResultSet rs;
        DefaultTableModel table = (DefaultTableModel)jTable1.getModel();
        int row = jTable1.getSelectedRow();
        String cell = jTable1.getModel().getValueAt(row, 0).toString();
        String query = "DELETE FROM `phones` where id="+cell;
        try {
            ps = phoneCNX.getConnection().prepareStatement(query);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Deleted Successfully! by "+uname);
            showTable();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        }

            
        
        
    }//GEN-LAST:event_jButton_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Delete;
    private javax.swing.JButton jButton_Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_home;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_Battery;
    private javax.swing.JTextField jTextField_Camera;
    private javax.swing.JTextField jTextField_Display;
    private javax.swing.JTextField jTextField_FingerPrint;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_Processor;
    private javax.swing.JTextField jTextField_Ram;
    private javax.swing.JTextField jTextField_Rom;
    private javax.swing.JTextField jTextField_os;
    private javax.swing.JTextField jTextField_price;
    private javax.swing.JTextField jTextField_vom;
    // End of variables declaration//GEN-END:variables
}
